### ISSUE TITLE
Datalink of On-board Camera

### ISSUE THREAD

**Issue by weiweikong** [UAVmatrix/UAVcast#1]
Hi,
I saw your project video about the testing of the `4Gmetry` with a fixed-wing UAV. There was an onboard camera but I am not sure that which data link is transferring the image streaming during the flight.

It seems that you were using `DynDNS` to conquer the IP switching issue to transfer control command between the ground station and fixed-wing UAV based on mavlink via 4G/LTE cell network. 

I searched the document and found that the camera was using `gStreamer` to connect with image streaming and mission planner using UDP. But it was not clear that 
> how could the image streaming transfer down to the ground station by 4G/LTE?

Also, I searched DynDNS and my local 3G/4G/LTE service, and it seems that the **UDP-based transfer is not support.** I also test the OpenCV-TCP-based method, https://github.com/weiweikong/tcp_opencv_image_streaming, and It was success, but the frame is quite slow less than 1Hz via 4G service.

I am personally not familiar with UDP-based image streaming tansfer by 4G. Any suggestion? Thanks.

**Comment by Sinamics** [comment]
Hi
gstreamer has embeded UDP protocoll for video streaming, so it`s quite easy to configure. 
You just seperate video and telemetry by a unique port.

I would advice you to post the question at uavmatrix.com. you will get support and information there.
I will close this thread as its more related to support rather then a issue.
