### ISSUE TITLE
camera.sh: should use rpicamsrc instead of raspivid + fdsrc

### ISSUE THREAD

**Issue by tp-m** [UAVmatrix/UAVcast#3]
https://github.com/thaytan/gst-rpicamsrc

**Comment by Sinamics** [comment]
I do see people complaints about increased latency using gst-rpicamsrc, based on this information I will close this thread. 
If you can point out any other good reason why we should use this wrapper then please re-open this post.

**Comment by Mocart96** [comment]
The current PI pipeline works not so perfect withmobile version of qground control. 
Maybe rpicamsrc can fix small problems related this app.
